### ISSUE TITLE
Sprint 1: Search for better (more realistic) ransomware sim

### ISSUE THREAD

**Issue by EnlightenedMint** [Tis-arch/Capstone#32]

**Comment by EnlightenedMint** [comment]
- [x] Search for more realistic ransomware simulators or defanged ransomware
- [x]  Compare newly found ransomware sims with ones previously used
- [x] Decide which ones will be used

**Comment by Tis-arch** [comment]
SEC 440 Ransomware created for this purpose. Yet to be neutered, but considered complete.
