### ISSUE TITLE
Set up targets

### ISSUE THREAD

**Issue by EnlightenedMint** [Tis-arch/Capstone#5]
Set up targets and basic networking

**Comment by EnlightenedMint** [comment]
- [x] Turn on VMs

**Comment by EnlightenedMint** [comment]
- [x] Create a diagram of the network layout
- [x] Set up network according to diagram

**Comment by Tis-arch** [comment]
We've been told the sysadmin 1 course has a nearly perfect architecture for the type of networks we'll be working with
